[workspace]
members = [
    "./",
    "./katalogos",
    "./paideia",
    "./diakritikos",
    "./phonetikos",
    "./phonologia"
]

[package]
name = "glossa"
version = "0.1.0"
edition = "2021"

[dependencies]
