[workspace]
members = [
    "./",
    "./katalogos",
    "./paideia",
    "./diakritikos",
    "./glossa",
    "./glossa/phonetikos",
    "./glossa/phonologia",
    "./glossa/metaphrastees",
]

[package]
name = "athyrma"
version = "0.1.0"
edition = "2021"

[dependencies]
